# netlify.toml at repo root

[build]
  # Explicitly set base directory to repository root
  base = "."
  # Command to build the specific frontend package from the root
  # 1. Install dependencies for the workspace
  # 2. Build the specific frontend package using pnpm filter
  command = "pnpm install --frozen-lockfile && pnpm --filter next-cloudflare-template run build"
  # Publish the output directory of the frontend package, relative to the root
  publish = "ai_dropship_frontend/out"

[build.environment]
  # Specify the pnpm version Netlify should use
  PNPM_VERSION = "8"
  # Set NODE_VERSION if needed, Netlify often defaults to a reasonable LTS
  # NODE_VERSION = "22"

